version: '3'

services:
  java:
    build: .
    container_name: java
    working_dir: /app
    tty: true
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
      - maven:/root/.m2/repository
      - extensions:/root/.vscode-server/extensions
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ddd-practice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
      - ./db:/etc/mysql/conf.d
    ports:
      - 3307:3306

volumes:
  maven:
  extensions:
  mysql:
